#!/usr/bin/env python3
"""Offline subsets of the already-shipped OFL font sources; no runtime fonts."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import math
ROOT = Path(__file__).resolve().parent
FONTS = ROOT.parent / 'nova/fonts'
sets = [('o34', 'Orbitron-700.ttf', 34, ' ABCDEFGHIKLNOPRSTUW'),
        ('o20', 'Orbitron-700.ttf', 20, '0123456789%'),
        ('o18', 'Orbitron-700.ttf', 18, '0123456789:-'),
        ('r14', 'Rajdhani-600.ttf', 14, ' ABCDEFGHIKLMNOPRSTUVWY'),
        ('r15', 'Rajdhani-600.ttf', 15, ' ABCDEFGHIKLMNOPRSTUVWY')]
alpha=[]
lines=['/* Generated by generate_points_assets.py. OFL sources: nova/fonts. */']
for name, filename, size, chars in sets:
    font=ImageFont.truetype(str(FONTS/filename),size*4)
    glyphs=[]
    for ch in chars:
        x,y,r,b=font.getbbox(ch,anchor='ls')
        x=math.floor(x/4)-1;y=math.floor(y/4)-1;r=math.ceil(r/4)+1;b=math.ceil(b/4)+1
        bitmap=Image.new('L',((r-x)*4,(b-y)*4))
        ImageDraw.Draw(bitmap).text((-x*4,-y*4),ch,font=font,fill=255,anchor='ls')
        bitmap=bitmap.resize((r-x,b-y),Image.Resampling.LANCZOS)
        glyphs.append('{%d,%d,%d,%d,%d,%d,%d}'%(ord(ch),x,y,r-x,b-y,round(font.getlength(ch)*64),len(alpha)))
        alpha.extend(bitmap.tobytes())
    lines += ['static const face_glyph ps_g_'+name+'[]={'+','.join(glyphs)+'};',
              f'static const face_font ps_f_{name}={{ps_g_{name},sizeof(ps_g_{name})/sizeof(ps_g_{name}[0])}};']
lines.append('static const uint8_t points_alpha[]={\n'+',\n'.join(','.join(map(str,alpha[i:i+32])) for i in range(0,len(alpha),32))+'\n};')
ROOT.joinpath('points_assets.inc').write_text('\n'.join(lines)+'\n')
print('Points glyph alpha bytes:',len(alpha))
