#!/usr/bin/env python3
"""Generate bounded antialiased font subsets from the reference's actual OFL fonts."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import math,hashlib,json
ROOT=Path(__file__).resolve().parent
FONTS=ROOT.parent/'nova/fonts'
sets=[('o40','Orbitron-700.ttf',40,'0123456789:-'),('o54','Orbitron-700.ttf',54,'0123456789-'),('o56','Orbitron-500.ttf',56,'0123456789:-'),('o26','Orbitron-500.ttf',26,'0123456789:-'),('o16','Orbitron-500.ttf',16,'0123456789-'),('o14','Orbitron-500.ttf',14,'0123456789:-'),('o13','Orbitron-700.ttf',13,'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'),('o12','Orbitron-500.ttf',12,'0123456789-%'),('o10','Orbitron-500.ttf',10,'0123456789-BCD '),('o9','Orbitron-500.ttf',9,'0123456789-%ABHMST '),('r12','Rajdhani-500.ttf',12,''),('r11','Rajdhani-500.ttf',11,''),('r10','Rajdhani-500.ttf',10,''),('r9','Rajdhani-500.ttf',9,''),('r7','Rajdhani-500.ttf',7,''),('rp11','Rajdhani-600.ttf',11,''),('m11','ShareTechMono-Regular.ttf',11,''),('m10','ShareTechMono-Regular.ttf',10,''),('m34','ShareTechMono-Regular.ttf',34,'0123456789:-')]
sets += [('f2_o104','Orbitron-700.ttf',104,'0123456789-'),('f2_o48','Orbitron-700.ttf',48,'0123456789:-'),('f2_o36','Orbitron-700.ttf',36,'0123456789:-'),('f2_o34','Orbitron-700.ttf',34,'0123456789:-'),('f2_o24','Orbitron-700.ttf',24,'0123456789:-'),('f2_r62','Rajdhani-600.ttf',62,'0123456789:-'),('f2_r54','Rajdhani-600.ttf',54,'0123456789-')]
data=[];lines=['/* Generated by faces/generate_assets.py; source font licenses are in nova/fonts. */']
for name,font,size,chars in sets:
 chars=chars or ''.join(chr(i) for i in range(32,91))
 ff=ImageFont.truetype(str(FONTS/font),size*4);rows=[]
 for ch in chars:
  x,y,r,b=ff.getbbox(ch,anchor='ls');x=math.floor(x/4)-1;y=math.floor(y/4)-1;r=math.ceil(r/4)+1;b=math.ceil(b/4)+1
  im=Image.new('L',((r-x)*4,(b-y)*4));ImageDraw.Draw(im).text((-x*4,-y*4),ch,font=ff,fill=255,anchor='ls');im=im.resize((r-x,b-y),Image.Resampling.LANCZOS)
  rows.append('{%d,%d,%d,%d,%d,%d,%d}'%(ord(ch),x,y,r-x,b-y,round(ff.getlength(ch)*64),len(data)));data.extend(im.tobytes())
 lines.append('static const face_glyph fg_'+name+'[]={'+','.join(rows)+'};')
 lines.append('static const face_font ff_'+name+'={fg_'+name+',sizeof(fg_'+name+')/sizeof(fg_'+name+'[0])};')
lines.append('static const uint8_t face_alpha[]={\n'+',\n'.join(','.join(map(str,data[i:i+32])) for i in range(0,len(data),32))+'\n};')
ROOT.joinpath('assets.inc').write_text('\n'.join(lines)+'\n')
print('face glyph bytes',len(data))

# Source-equation lookup tables keep the animated second collection integer-only.
# The reference's smooth noise samples wrap at 128 lattice cells; the initial
# field is identical to the HTML hash before bounded tiling.
extra=['/* Generated from the supplied Watch Faces II SVG equations. */']
def array(kind,name,values,cols=24):
 extra.append('static const '+kind+' '+name+'[]={\n'+',\n'.join(','.join(map(str,values[i:i+cols])) for i in range(0,len(values),cols))+'\n};')
array('uint8_t','f2_radial_alpha',[round(153*(1-math.sqrt(i/1024))) for i in range(1025)])
noise=[]
for y in range(128):
 for x in range(128):
  v=math.sin(x*127.1+y*311.7)*43758.5453
  noise.append(round((v-math.floor(v))*65535))
array('uint16_t','f2_noise',noise)
stars=[]
for i in range(46):
 a=math.sin(i*127.1)*43758.5453;b=math.sin(i*311.7)*12543.321
 stars += [math.floor((a-math.floor(a))*240+.5),math.floor((b-math.floor(b))*240+.5),round(((i%3)+1.4)*8)]
array('uint8_t','f2_stars',stars)
ROOT.joinpath('collection_two_assets.inc').write_text('\n'.join(extra)+'\n')
