#!/usr/bin/env python3
"""Build Calendar collection assets from the retained, owner-reference OFL fonts.

All floating-point geometry and font rasterization occurs here, never on watch.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, ImageFilter, ImageChops
import math

ROOT = Path(__file__).resolve().parent
FONTS = ROOT.parent / 'nova/fonts'
DIGITS = '0123456789:-'
UPPER = ''.join(chr(i) for i in range(32, 91)) + '\u00b7'
SETS = [(f'o{size}', 'Orbitron-700.ttf', size, DIGITS, 0)
        for size in (28, 36, 38, 40, 42, 46, 52)]
SETS += [('o9', 'Orbitron-500.ttf', 9, DIGITS, 0),
         ('o11', 'Orbitron-500.ttf', 11, DIGITS + '%', 0),
         ('o12', 'Orbitron-700.ttf', 12, DIGITS, 0),
         ('date', 'Orbitron-700.ttf', 120, '0123456789-', -5),
         ('o46_halo', 'Orbitron-700.ttf', 46, DIGITS, 14)]
SETS += [(f'r{size}', 'Rajdhani-500.ttf', size, UPPER, 0) for size in (9, 10, 11)]
SETS += [(f'r{size}b', 'Rajdhani-600.ttf', size, UPPER, 0) for size in (9, 10, 11)]
SETS += [(f'r{size}_halo', 'Rajdhani-500.ttf', size, UPPER, 8) for size in (10, 11)]

alpha = []
lines = ['/* Generated by generate_calendar_assets.py. OFL licenses: nova/fonts. */']
for name, filename, size, chars, stroke in SETS:
    font = ImageFont.truetype(str(FONTS / filename), size * 4)
    glyphs = []
    for ch in chars:
        x, y, r, b = font.getbbox(ch, anchor='ls')
        pad = math.ceil(abs(stroke) / 4) + 1
        x = math.floor(x / 4) - pad
        y = math.floor(y / 4) - pad
        r = math.ceil(r / 4) + pad
        b = math.ceil(b / 4) + pad
        bitmap = Image.new('L', ((r - x) * 4, (b - y) * 4))
        ImageDraw.Draw(bitmap).text((-x * 4, -y * 4), ch, font=font, fill=255, anchor='ls')
        if stroke:
            outer = bitmap.filter(ImageFilter.MaxFilter(abs(stroke) * 2 + 1))
            bitmap = ImageChops.subtract(outer, bitmap.filter(ImageFilter.MinFilter(-stroke * 2 + 1))) if stroke < 0 else outer
        bitmap = bitmap.resize((r - x, b - y), Image.Resampling.LANCZOS)
        glyphs.append('{%d,%d,%d,%d,%d,%d,%d}' %
                      (ord(ch), x, y, r - x, b - y, round(font.getlength(ch) * 64), len(alpha)))
        alpha.extend(bitmap.tobytes())
    lines += ['static const face_glyph fc_g_' + name + '[]={' + ','.join(glyphs) + '};',
              f'static const face_font fc_f_{name}={{fc_g_{name},sizeof(fc_g_{name})/sizeof(fc_g_{name}[0])}};']
lines.append('static const uint8_t calendar_alpha[]={\n' + ',\n'.join(
    ','.join(map(str, alpha[i:i + 32])) for i in range(0, len(alpha), 32)) + '\n};')
# Fixed annulus coverage avoids repeated line rasterization for static dial geometry.
lines.append('typedef struct { uint16_t pixel,angle; uint8_t alpha; } fc_ring_pixel;')
for radius, width in ((96, 7), (98, 10)):
    pixels = []
    for y in range(240):
        for x in range(240):
            covered = sum((radius - width / 2) ** 2 <= (x + sx - 120) ** 2 + (y + sy - 120) ** 2 <= (radius + width / 2) ** 2
                          for sx in (.25, .75) for sy in (.25, .75))
            if covered:
                angle = round((math.degrees(math.atan2(x + .5 - 120, 120 - y - .5)) % 360) * 128)
                pixels.append('{%d,%d,%d}' % (y * 240 + x, angle, covered * 255 // 4))
    lines.append(f'static const fc_ring_pixel fc_ring_{radius}[]={{\n' + ',\n'.join(
        ','.join(pixels[i:i + 8]) for i in range(0, len(pixels), 8)) + '\n};')
ROOT.joinpath('calendar_assets.inc').write_text('\n'.join(lines) + '\n')
print('Calendar alpha bytes:', len(alpha))
