#pragma once
#define WATCH_BASE_FACE_NAMES "NOVA","ANALOG","RADAR","HEX","TERMINAL","MINIMAL","BINARY","CHRONO","AURORA","HORIZON","GIANT","MOON","TOPO","ORRERY","FLIP","MATRIX","GRID","RIBBON","YEAR","24H","AGENDA","DATE","DOTS","PROGRESS","NEXT","RING","LADDER","DAYLINE","TRIPLE","STATUS","BOARD","WORKDAY","UP NEXT"
#define WATCH_CONTEXT_FACE_NAMES WATCH_BASE_FACE_NAMES,"CONTEXTS"
#define WATCH_CONTEXT_FACE_COUNT 34u
#ifdef WATCH_CONTEXTS_CLIENT
#define WATCH_FACE_COUNT WATCH_CONTEXT_FACE_COUNT
#define WATCH_FACE_NAMES WATCH_CONTEXT_FACE_NAMES
#else
#define WATCH_FACE_COUNT 33u
#define WATCH_FACE_NAMES WATCH_BASE_FACE_NAMES
#endif
