#!/usr/bin/env python3
"""Offline NOVA-7 assets. Requires Pillow, numpy and Inkscape; no firmware dependency.

Original 240x240 geometry comes from reference/NOVA-7-original.html. The TTFs
are unmodified SIL OFL fonts. Assets include antialiasing and the source glow.
"""
from pathlib import Path
import math, re, subprocess, os, tempfile
import numpy as np
from PIL import Image, ImageDraw, ImageFont, ImageFilter
ROOT = Path(__file__).resolve().parent
OUT = ROOT / 'assets.inc'
S = 4
font_dir = ROOT / 'fonts'

def font(name,size): return ImageFont.truetype(str(font_dir/name),size*S)
def arr(name,ctype,values,per=12):
    lines=[f'static const {ctype} {name}[] = {{']
    for i in range(0,len(values),per): lines.append('    '+','.join(str(v) for v in values[i:i+per])+',')
    return '\n'.join(lines+['};'])
def rgb565(rgb):
    r,g,b=map(int,rgb[:3]);return ((r>>3)<<11)|((g>>2)<<5)|(b>>3)
def blend565(c,a): return rgb565([round(x*a) for x in c])
lines=['/* Generated by generate_assets.py. Do not hand-edit. */']
# Rasterize the immutable part of the actual SVG. No font substitutions.
source=(ROOT/'reference/reference-104218.svg').read_text()
source=re.sub(r'<circle[^>]*(?:id="(?:sec|dot)"|transform="rotate\((?:60|-135) 120 120\)")[^>]*/>','',source)
source=re.sub(r'<text.*?</text>','',source,flags=re.S)
source=re.sub(r'<circle cx="92"[^>]*/>','',source)
source=source.replace('<rect x="105" y="190" width="25.2" height="2" rx="1" fill="#3dff9a"/>','')
# Keep original BATTERY text as the only immutable label.
source=source.replace('</svg>','<text x="120" y="171" text-anchor="middle" font-family="Rajdhani" font-size="9" font-weight="500" letter-spacing="2" fill="#6b7c80">BATTERY</text></svg>')
with tempfile.TemporaryDirectory() as d:
    d=Path(d);(d/'static.svg').write_text(source)
    (d/'fonts.conf').write_text(f'<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd"><fontconfig><include>/etc/fonts/fonts.conf</include><dir>{font_dir}</dir><cachedir>{d}/cache</cachedir></fontconfig>')
    env=dict(os.environ,FONTCONFIG_FILE=str(d/'fonts.conf'),INKSCAPE_PROFILE_DIR=str(d/'inkscape'))
    subprocess.run(['inkscape',str(d/'static.svg'),'--export-type=png',f'--export-filename={d}/static.png'],env=env,check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    pixels=np.array(Image.open(d/'static.png').convert('RGB'))
    colors=[]; spans=[]
    for y,row in enumerate(pixels):
        x=0
        while x<240:
            if not rgb565(row[x]): x+=1;continue
            begin=x;offset=len(colors)
            while x<240 and rgb565(row[x]): colors.append(rgb565(row[x]));x+=1
            spans.append(f'{{{y*240+begin},{x-begin},{offset}}}')
    lines += [arr('nova_base_pixels','uint16_t',colors),arr('nova_base_spans','nova_span',spans,4)]
# Precomputed thin annuli. Positions/angles/coverage are immutable; render only
# does a phase shift and tests the dash pattern. 0 angle starts at 3 o'clock.
def ring(name,r,width,color,glow=False):
    points=[]
    # Gaussian convolution of a narrow strip approximates the SVG radial glow.
    for y in range(240):
      for x in range(240):
        dx=x+.5-120;dy=y+.5-120;rad=math.hypot(dx,dy);distance=abs(rad-r)
        if distance > (7 if glow else 1.2): continue
        alpha=0
        for oy in (0.125,0.375,0.625,0.875):
          for ox in (0.125,0.375,0.625,0.875):
            alpha += abs(math.hypot(x+ox-120,y+oy-120)-r)<=width/2
        alpha/=16
        if glow:
            blur=.5*(math.erf((distance+width/2)/(2.2*math.sqrt(2)))-math.erf((distance-width/2)/(2.2*math.sqrt(2))))
            alpha=alpha+(1-alpha)*blur
        c=blend565(color,alpha)
        if not c: continue
        angle=round((math.atan2(dy,dx)%math.tau)*65536/math.tau)%65536
        points.append(f'{{{y*240+x},{angle},{round(alpha*255) if glow else c}}}')
    lines.append(arr(name,'nova_ring_pixel',points,4));print(name,len(points))
ring('nova_seconds',98,2.5,(25,227,255),True)
ring('nova_ring82',82,1,(14,79,92))
ring('nova_ring76',76,1,(9,79,89))
# Glyph masks at 4x resolution, downsampled with real font hinting. Metrics in
# quarter-pixels preserve proportional Orbitron widths and SVG textLength=132.
glyph_data=[]; glyphs=[]
sets=[('big','Orbitron-700.ttf',40,'0123456789:-',True),
      ('small','Orbitron-500.ttf',9,'0123456789-APM',False),
      ('battery','Orbitron-500.ttf',13,'0123456789-%',False),
      ('date','Rajdhani-600.ttf',12,'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ -',False),
      ('status','Rajdhani-500.ttf',9,'RTCUNSET',False)]
for setname,filename,size,chars,glow in sets:
    ff=font(filename,size); entries=[]
    for ch in chars:
        box=ff.getbbox(ch,anchor='ls');pad=7 if glow else 1
        left=math.floor(box[0]/S)-pad;top=math.floor(box[1]/S)-pad
        right=math.ceil(box[2]/S)+pad;bottom=math.ceil(box[3]/S)+pad
        w=right-left;h=bottom-top
        im=Image.new('L',(w*S,h*S));draw=ImageDraw.Draw(im)
        draw.text((-left*S,-top*S),ch,font=ff,fill=255,anchor='ls')
        im=im.resize((w,h),Image.Resampling.LANCZOS)
        if glow:
            blur=im.filter(ImageFilter.GaussianBlur(2.2))
            a=np.array(im,dtype=np.uint16);b=np.array(blur,dtype=np.uint16)
            im=Image.fromarray((a+((255-a)*b+127)//255).astype('uint8'))
        offset=len(glyph_data);glyph_data.extend(im.tobytes())
        entries.append(f'{{{ord(ch)},{left},{top},{w},{h},{round(ff.getlength(ch)/S*256)},{offset}}}')
    lines.append(arr('nova_'+setname+'_glyphs','nova_glyph',entries,3))
lines.append(arr('nova_glyph_alpha','uint8_t',glyph_data,24))
# The white orbit dot preserves the source 3.4px radius + 2.2px blur. 16 phase
# variants give smooth quarter-pixel positions without runtime interpolation.
sprites=[]
for py in range(4):
 for px in range(4):
    im=Image.new('L',(22*S,22*S));d=ImageDraw.Draw(im)
    cx=(10+px/4)*S;cy=(10+py/4)*S;r=3.4*S
    d.ellipse((cx-r,cy-r,cx+r,cy+r),fill=255)
    im=im.resize((22,22),Image.Resampling.LANCZOS);a=np.array(im,dtype=np.uint16);b=np.array(im.filter(ImageFilter.GaussianBlur(2.2)),dtype=np.uint16)
    sprites.extend((a+((255-a)*b+127)//255).astype('uint8').tobytes())
lines.append(arr('nova_dot_alpha','uint8_t',sprites,24))
# Round leading arc cap. Only its left half is needed: the annular arc covers
# the right half at 12 o'clock. Alpha blends over ticks rather than erasing them.
im=Image.new('L',(16*S,16*S));d=ImageDraw.Draw(im);r=1.25*S
# Centers align to the SVG coordinate (120,22), not pixel centers.
d.ellipse((8*S-r,8*S-r,8*S+r,8*S+r),fill=255)
im=im.resize((16,16),Image.Resampling.LANCZOS);a=np.array(im,dtype=np.uint16);b=np.array(im.filter(ImageFilter.GaussianBlur(2.2)),dtype=np.uint16)
cap=(a+((255-a)*b+127)//255).astype('uint8')
lines.append(arr('nova_start_cap','uint8_t',cap.tobytes(),16))

lines.append(arr('nova_sine','int16_t',[round(math.sin(math.radians(i))*32767) for i in range(361)],16))
OUT.write_text('\n\n'.join(lines)+'\n')
print('glyph bytes',len(glyph_data),'generated source bytes',OUT.stat().st_size)
